config/routes.rb
Rails.application.routes.draw do

	get '/' => 'site#index', as: 'site_index'
	#get 'site/index'
	#resources :boulders
	#post 'boulders/upload_picture' => 'boulders#upload_picture'



	namespace :api do
		get		'boulder'	=>	'boulders#index'
		post	'boulder'	=>	'boulders#create', as: 'boulder_create'
		get		'boulder/:id'	=>	'boulders#read', as: 'boulder_read'
		put		'boulder/:id'	=>	'boulders#update', as: 'boulder_update'
		delete	'boulder/:id'	=>	'boulders#delte', as: 'boulder_delete'
	end

end

app/models/boulder.rb
class Boulder < ActiveRecord::Base

	scope :posted, -> { where posted }
	scope :not_posted, -> { where not_posted }

	enum status: {  
		not_posted: 0,
		posted: 1,
	}

	def posted 
		self.status = :posted
	end

	def not_posted 
		self.status = :not_posted
	end

end

app/controllers/api/boulders_controller.rb
class Api::BouldersController < ApplicationController

	skip_before_filter :verify_authenticity_token, only: [:create]

	# GET
	def index
		limit = params[:limit] || 10
		offset = params[:offset] || 0
		render json: Boulder.posted.offset(offset).limit(limit).order(:id), :root => false
	end

	# POST
	def create
		picture = params[:picture]
		angle = params[:picture_angle]
		
		boulder = create_boulder(params)

		if(!boulder.blank? && !picture.blank?) then
			write_picture(boulder, picture, angle)
			render json: {boulder_id: boulder.id}
		end
	end

	# GET :id
	def read
		boulder_id = params[:id]
		boulder = Boulder.find(boulder_id)
		render json: boulder, :root => false
	end

	protected

	def create_boulder(params)
		boulder = Boulder.new
		boulder.name = params[:boulder_name]
		boulder.location = params[:boulder_loc]
		boulder.latitude = params[:boulder_latitude]
		boulder.longitude = params[:boulder_longitude]
		boulder.save
		
		return boulder
	end

	def write_picture(boulder, picture, angle)
		file_name = "boulder-#{boulder.id}.jpg"
		File.open(Rails.root.join('public', PICTURE_PATH, file_name), 'wb') do |file|
			file.write(picture.read)
		end
		boulder.picture = file_name
		boulder.posted
		boulder.save

		rotate_picture(boulder, angle)		
		make_thumbnail(boulder)
	end

	def rotate_picture(boulder, angle)
		image = MiniMagick::Image.new(Rails.root.join('public', PICTURE_PATH, boulder.picture))
		image.rotate angle
	end

	def make_thumbnail(boulder)
		image = MiniMagick::Image.open(Rails.root.join('public', PICTURE_PATH, boulder.picture))
		image.resize "250x250"
		image.write Rails.root.join('public', THUMBNAIL_PATH, boulder.picture)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boulders_controller.rb
class BouldersController < ApplicationController

	skip_before_filter :verify_authenticity_token, only: [:upload_picture]

	def index
		@boulder = Boulder.posted
	end

	def new
		@boulder = Boulder.create
	end

	def create
	end

	def upload_picture
		picture = params[:picture]
		boulder_id = params[:boulder_id].split("_")[2]
		boulder = Boulder.find(boulder_id)

		if(!boulder.blank? || !picture.blank?) then
			write_picture(boulder, picture)
			render json: {response: "OK"}
		end

	end

	def show
		@boulder = Boulder.find(params[:id])
	end

	def update
	end

	protected
	def write_picture(boulder, picture)
		file_name = Time.now.strftime('%Y%m%d%H%M%S%L') + "-#{boulder.id}.jpg"
		File.open(Rails.root.join('public', 'uploads', file_name), 'wb') do |file|
			file.write(picture.read)
		end
		boulder.picture = file_name
		boulder.save
	end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
  end

end

app/helpers/api/boulders_helper.rb
module Api::BouldersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boulders_helper.rb
module BouldersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/boulders/index.html.erb
<%= content_tag_for(:li, @boulder.each) do |boulder| %>
	<%= boulder.name %>
	<%= boulder.picture %>
<% end %>

app/views/boulders/new.html.erb
<div class="row">
	<div class="col-xs-6 col-md-9">
		<div class="icon_big">
			<span class="glyphicon glyphicon-camera icon_big" aria-hidden="true" id="camera_picture"></span>		
		</div>
	</div>
	<div class="col-xs-6 col-md-9">
		<div class="icon_big">
			<span class="glyphicon glyphicon-folder-open icon_big" aria-hidden="true" id="local_picture"></span>
		</div>
	</div>
</div>

<%= form_for @boulder, remote: true, authenticity_token: true do |f| %>
	<%= f.file_field :picture, id: "pictureToUpload", onchange: "pictureTaken();", accept: "image/*", class: "hidden", capture: "camera" %><br>
	<%= f.file_field :picture, id: "fileToUpload", onchange: "fileSelected();", accept: "image/*", class: "hidden"%><br>
<% end %>
  
<div id="details"></div>
<div id="progress"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gravel</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag 'bootstrap/dist/css/bootstrap.css', media: 'all'%>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application', defer: :true%>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
	<%= render 'layouts/partials/header' %>
	<div id="content">
		<%= yield %>
	</div>
</div>
	<%= render 'layouts/partials/footer' %>


</body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer>
	<div class="container-fluid">
		<p class="text-muted">Gravel for Ironhack 2014</p>
	</div>
</footer>

app/views/layouts/partials/_header.html.erb
<header class="class-header row">
	<div class="col-xs-12 col-md-9">
		<h1 class="text-center"><%= link_to('Gravel', site_index_path) %></h1>
	</div>
	<div id="user_panel" class="col-md-3 hidden-xs hidden-sm">
		<p>Welcome Username</p>
		<ul>
			<li><a href="">Profile</a></li>
			<li><a href="#boulders">Boulders</a></li>
			<li><a href="#boulder">New boulder</a></li>
		</ul>
	</div>
</header>

<div id="mini_user_panel" class="row hidden-md hidden-lg">
	<a href="">
		<div class="col-xs-4">
			Profile
		</div>
	</a>
	<a href="#boulders">
		<div class="col-xs-4">
			Boulders
		</div>
	</a>
	<a href="#boulder">
		<div class="col-xs-4">
			New boulder
		</div>
	</a>
</div>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>